"""initial

Revision ID: dea71c5c548c
Revises:
Create Date: 2026-06-04 18:54:31.991009

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "dea71c5c548c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
