apiVersion: v1
kind: Secret
metadata:
  name: oauth-secrets
  namespace: recipe-platform
type: Opaque
stringData:
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
  YANDEX_CLIENT_ID: ""
  YANDEX_CLIENT_SECRET: ""
